yelp-debug: check if __STDC_VERSION__ is defined
__STDC_VERSION__ is defined only when switch -std=c99 (and newer
standards) is defined. This can break the build with error:

error: "__STDC_VERSION__" is not defined

https://bugzilla.gnome.org/show_bug.cgi?id=744454