Remove the unused encoding and language code from YelpManDocument
Error: UNUSED_VALUE (CWE-563): [#def25]
yelp-3.28.1/libyelp/yelp-man-document.c:422: value_overwrite: Overwriting previous write to "encoding" with value from "langmap[i].encoding".
yelp-3.28.1/libyelp/yelp-man-document.c:416: assigned_pointer: Assigning value from ""ISO-8859-1"" to "encoding" here, but that stored value is overwritten before it can be used.
  414|       encoding = g_getenv("MAN_ENCODING");
  415|       if (encoding == NULL)
  416|->  encoding = "ISO-8859-1";
  417|
  418|       if (language != NULL) {

Error: CLANG_WARNING: [#def26]
yelp-3.28.1/libyelp/yelp-man-document.c:416:2: warning: Value stored to 'encoding' is never read
        encoding = "ISO-8859-1";
        ^          ~~~~~~~~~~~~
yelp-3.28.1/libyelp/yelp-man-document.c:416:2: note: Value stored to 'encoding' is never read
        encoding = "ISO-8859-1";
        ^          ~~~~~~~~~~~~
  414|       encoding = g_getenv("MAN_ENCODING");
  415|       if (encoding == NULL)
  416|->  encoding = "ISO-8859-1";
  417|
  418|       if (language != NULL) {

Error: CLANG_WARNING: [#def27]
yelp-3.28.1/libyelp/yelp-man-document.c:422:3: warning: Value stored to 'encoding' is never read
                encoding = langmap[i].encoding;
                ^          ~~~~~~~~~~~~~~~~~~~
yelp-3.28.1/libyelp/yelp-man-document.c:422:3: note: Value stored to 'encoding' is never read
                encoding = langmap[i].encoding;
                ^          ~~~~~~~~~~~~~~~~~~~
  420|    for (i = 0; langmap[i].language != NULL; i++) {
  421|        if (g_str_equal (language, langmap[i].language)) {
  422|->   encoding = langmap[i].encoding;
  423|     break;
  424|        }